repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.4'
    hooks:
    -   id: autopep8
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
